"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, Check, CheckCircle2, ChevronRight, Layers, ListChecks, RotateCcw, Trophy } from "lucide-react";
import type { Lesson } from "@/lib/minna/types";
import { progressMetrics, recordQuiz } from "@/lib/minna/progress";
import { useLessonProgress } from "./use-progress";
import { Flashcards, VocabularyList } from "./vocabulary";
import { VocabularyQuiz } from "./vocabulary-quiz";
import { SectionContent } from "./content";
import { Practice } from "./practice";

const tabs = ["Tổng quan", "Từ vựng", "Flashcard", "Quiz từ vựng", "Ngữ pháp", "Bài tập", "Tiến độ"];
export function LessonDetail({ lesson, previous, next }: { lesson: Lesson; previous: number | null; next: number | null }) {
  const [tab, setTab] = useState(0);
  const [focus, setFocus] = useState<string[] | null>(null);
  const { progress, update, ready, storageFailed } = useLessonProgress(lesson.id);
  const metrics = progressMetrics(lesson, progress);
  const choose = (index: number) => { setTab(index); if (index !== 2) setFocus(null); };
  const mark = (id: string, state: "learned" | "review") => update(p => ({ ...p,
    learned: state === "learned" ? [...new Set([...p.learned, id])] : p.learned.filter(w => w !== id),
    review: state === "review" ? [...new Set([...p.review, id])] : p.review.filter(w => w !== id) }));
  const review = (ids: string[]) => { setFocus(ids); setTab(2); };
  const stats = <div className="mn-stat-grid four"><div><strong>{metrics.learned}<small> / {lesson.vocabulary.length}</small></strong><span>Từ đã nhớ</span></div><div><strong>{progress.quiz.bestTotal ? `${progress.quiz.bestCorrect}/${progress.quiz.bestTotal}` : "—"}</strong><span>Quiz tốt nhất{progress.quiz.bestTotal > 0 ? ` · ${Math.round(progress.quiz.bestCorrect / progress.quiz.bestTotal * 100)}%` : ""}</span></div><div><strong>{metrics.grammar}<small> / {lesson.grammar.length}</small></strong><span>Ngữ pháp đã học</span></div><div><strong>{metrics.practice}<small> / {lesson.exercises.length}</small></strong><span>Bài tập đã làm · tự kiểm tra</span></div></div>;
  return <>
    <div className="mn-breadcrumb"><Link href="/minna"><ArrowLeft size={15} /> Tất cả bài học</Link><ChevronRight size={14} /><span>Bài {lesson.id}</span></div>
    <header className="mn-lesson-header"><div><span className="mn-kicker">MINNA NO NIHONGO · BÀI {String(lesson.id).padStart(2, "0")}</span><h1>Học từng từ.<br /><em>Hiểu từng câu.</em></h1><p>{lesson.title}</p><div className="mn-card-counts"><span>{lesson.vocabulary.length} từ vựng</span><span>{lesson.grammar.length} mục ngữ pháp</span><span>{lesson.exercises.length} bài tập</span></div></div><div className="mn-progress-dial" style={{ background: `conic-gradient(var(--coral) ${metrics.overall}%, var(--line) 0)` }}><div><strong>{metrics.overall}%</strong><span>tiến độ bài học</span></div></div></header>
    <nav className="mn-tabs" aria-label="Nội dung bài học">{tabs.map((label, i) => <button key={label} aria-current={tab === i ? "page" : undefined} onClick={() => choose(i)}>{label}</button>)}</nav>
    {storageFailed && <p className="mn-notice" role="alert">Trình duyệt không cho lưu dữ liệu. Tiến độ hiện chỉ giữ trong phiên này; hãy bật bộ nhớ trình duyệt để giữ sau khi tải lại.</p>}
    {!ready ? <p className="mn-empty">Đang tải tiến độ học tập…</p> : <div className="mn-tab-content" key={tab}>
      {tab === 0 && <>{stats}<div className="mn-overview-grid"><section className="mn-panel"><span className="mn-kicker">BẮT ĐẦU TỪ ĐÂU?</span><h2>Một bài học, theo nhịp của bạn.</h2><p className="mn-muted">Làm quen với từ mới, ôn bằng thẻ, kiểm tra trí nhớ rồi áp dụng vào ngữ pháp và bài tập. Bạn có thể chuyển phần bất cứ lúc nào.</p><div className="mn-study-steps">{[[1, "Khám phá từ vựng", "Đọc kana, kanji và nghĩa tiếng Việt.", BookOpen], [2, "Ghi nhớ bằng flashcard", "Lật thẻ, tự đánh giá và chọn từ cần ôn.", Layers], [3, "Thử sức với quiz", "Kiểm tra từ đã học, xem lại những từ sai.", Trophy], [4, "Hiểu ngữ pháp", "Đọc cách dùng, ví dụ và xem video nếu có.", BookOpen], [5, "Thực hành bài tập", "Điền câu trả lời, chọn từ và tự đối chiếu.", ListChecks], [6, "Nhìn lại tiến độ", "Ôn từ khó và tiếp tục phần chưa hoàn thành.", CheckCircle2]].map(([index, label, description, Icon]) => { const StepIcon = Icon as typeof BookOpen; return <button key={Number(index)} onClick={() => choose(Number(index))}><span><StepIcon size={19} /></span><div><strong>{String(label)}</strong><small>{String(description)}</small></div><ArrowRight size={16} /></button>; })}</div></section><aside className="mn-panel mn-topics"><span className="mn-kicker">TRONG BÀI NÀY</span><h2>Chủ điểm ngữ pháp</h2>{lesson.grammar.map((s, i) => <button key={s.id} onClick={() => choose(4)}><span>{String(i + 1).padStart(2, "0")}</span><strong>{s.title.replace(/^\d+[.．]\s*/, "")}</strong>{progress.grammar.includes(s.id) && <Check size={15} />}</button>)}<p className="mn-footnote">Nội dung giữ theo nguồn. Bài tập có thể chứa kiến thức ôn tập hoặc lỗi biên soạn của nguồn.</p></aside></div></>}
      {(tab === 1 || tab === 2 || tab === 3) && !lesson.vocabulary.length && <div className="mn-empty"><BookOpen size={34} /><h2>Chưa có bảng từ vựng trong nguồn</h2><p>Bạn vẫn có thể học đầy đủ ngữ pháp và làm bài tập của bài {lesson.id}.</p><button className="mn-button primary" onClick={() => choose(4)}>Học ngữ pháp <ArrowRight size={16} /></button></div>}
      {tab === 1 && lesson.vocabulary.length > 0 && <><div className="mn-heading"><div><span className="mn-kicker">TỪNG TỪ NHỎ, NỀN TẢNG LỚN</span><h2>Từ vựng · Bài {lesson.id}</h2></div><button className="mn-button" onClick={() => choose(2)}><Layers size={16} /> Học với flashcard</button></div><VocabularyList words={lesson.vocabulary} progress={progress} mark={mark} />{lesson.vocabularySections.map(s => <details className="mn-source-detail" key={s.id}><summary>Xem bảng từ vựng gốc · {s.title}</summary><SectionContent section={s} /></details>)}</>}
      {tab === 2 && lesson.vocabulary.length > 0 && <><div className="mn-heading"><div><span className="mn-kicker">LẬT THẺ · GHI NHỚ · ÔN LẠI</span><h2>{focus ? "Ôn bộ từ đã chọn" : "Flashcard từ vựng"}</h2></div>{focus && <button className="mn-button" onClick={() => setFocus(null)}>Học tất cả từ</button>}</div><Flashcards key={focus?.join(",") ?? "all"} words={focus ? lesson.vocabulary.filter(w => focus.includes(w.id)) : lesson.vocabulary} progress={progress} mark={mark} /><div className="mn-next-step"><span>Sẵn sàng kiểm tra trí nhớ?</span><button className="mn-button primary" onClick={() => choose(3)}>Làm quiz <ArrowRight size={16} /></button></div></>}
      {tab === 3 && lesson.vocabulary.length > 0 && <VocabularyQuiz words={lesson.vocabulary} onFinish={(correct, total, wrong) => update(p => recordQuiz(p, correct, total, wrong))} onReview={review} />}
      {tab === 4 && <><div className="mn-heading"><div><span className="mn-kicker">ĐỌC · HIỂU · ÁP DỤNG</span><h2>Ngữ pháp & ví dụ</h2></div><span className="mn-pill">{metrics.grammar} / {lesson.grammar.length} đã học</span></div><div className="mn-grammar-list">{lesson.grammar.map((section, i) => <details className="mn-grammar-card" key={section.id} open={i === 0}><summary><span className="mn-lesson-number">{String(i + 1).padStart(2, "0")}</span><h3>{section.title.replace(/^\d+[.．]\s*/, "")}</h3>{progress.grammar.includes(section.id) && <CheckCircle2 size={21} className="mn-success" />}</summary><div className="mn-grammar-body"><SectionContent section={section} /><button className={`mn-button ${progress.grammar.includes(section.id) ? "" : "primary"}`} onClick={() => update(p => ({ ...p, grammar: p.grammar.includes(section.id) ? p.grammar.filter(id => id !== section.id) : [...p.grammar, section.id] }))}><Check size={16} />{progress.grammar.includes(section.id) ? "Đã học · nhấn để bỏ đánh dấu" : "Đánh dấu đã học mục này"}</button></div></details>)}</div><div className="mn-next-step"><span>Áp dụng những gì vừa học</span><button className="mn-button primary" onClick={() => choose(5)}>Làm bài tập <ArrowRight size={16} /></button></div></>}
      {tab === 5 && <Practice lesson={lesson} progress={progress} update={update} />}
      {tab === 6 && <><div className="mn-heading"><div><span className="mn-kicker">NHÌN LẠI CHẶNG ĐƯỜNG</span><h2>Tiến độ bài {lesson.id}</h2></div><span className="mn-pill">Lưu trên thiết bị này</span></div>{stats}<div className="mn-panel"><h3>Tiếp tục từ nơi bạn cần</h3><p>{progress.review.length} từ được đánh dấu cần ôn · {progress.quiz.attempts} lượt quiz hoàn thành.</p>{progress.quiz.lastTotal > 0 && <p>Lượt quiz gần nhất: {progress.quiz.lastCorrect} / {progress.quiz.lastTotal} câu đúng.</p>}<div className="mn-actions"><button className="mn-button" disabled={!progress.review.length} onClick={() => review(progress.review)}><RotateCcw size={16} /> Ôn các từ cần nhớ</button><button className="mn-button" disabled={!progress.quiz.wrong.length} onClick={() => review(progress.quiz.wrong)}>Ôn từ sai lượt gần nhất</button><button className="mn-button primary" onClick={() => choose(metrics.grammar < lesson.grammar.length ? 4 : 5)}>Tiếp tục học <ArrowRight size={16} /></button></div><p className="mn-footnote">Tiến độ chung là trung bình của tỷ lệ từ đã nhớ, độ chính xác quiz tốt nhất, ngữ pháp đã học và bài tập đã làm. Mục không có dữ liệu được bỏ qua. Đây là tiến độ hoạt động, không phải chứng nhận thành thạo; bài tập gốc chưa được chấm.</p></div></>}
    </div>}
    <footer className="mn-lesson-footer"><a href={lesson.sourceUrl} target="_blank" rel="noreferrer">Nguồn bài học: Riki ↗</a><div>{previous && <Link href={`/minna/${previous}`}><ArrowLeft size={15} /> Bài {previous}</Link>}{next && <Link href={`/minna/${next}`}>Bài {next} <ArrowRight size={15} /></Link>}</div></footer>
  </>;
}
